name: flutter_speech_to_text
description: A powerful, easy-to-use Flutter plugin for real-time speech-to-text conversion using native iOS Speech Framework and Android SpeechRecognizer.
version: 1.1.0
homepage: https://github.com/JeromeGsq/flutter_speech_to_text
repository: https://github.com/JeromeGsq/flutter_speech_to_text
issue_tracker: https://github.com/JeromeGsq/flutter_speech_to_text/issues

topics:
  - speech-recognition
  - speech-to-text
  - voice
  - audio

screenshots:
  - description: 'Interface principale de transcription'
    path: documentation/screen1.png
  - description: 'Dialogue de permissions'
    path: documentation/screen2.png

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jeromegsq.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
      macos:
        pluginClass: SpeechToTextPlugin
